### ISSUE TITLE
Won't compile: GalacticGen.java can't find imports

### ISSUE THREAD

**Issue by mayhewsw** [gdtreebank/gdtreebank#1]
GalacticGen appears to reference a edu.jhu.util package which is not referenced in the pom.xml file, and I can't find it online. This appears to be some internal package. Any chance it could be released?

**Comment by wddabc** [comment]
Hi, Thanks for the interest in the work! I can confirm it happens to me as well when I open the project with IDE (Intellij idea), which didn't happen before. However, looks I can still do mvn compile in the commandline. Can you confirm that? This will help me locate the issue.

**Comment by mayhewsw** [comment]
mvn shows "BUILD SUCCESS", but that's because it doesn't find any source files ("No sources to compile"). Perhaps this is because the structure is non-standard? Maven expects src/main/java, but there is only src/main/<packages>

**Comment by mayhewsw** [comment]
When I move all directories in src/main to src/main/java, then mvn has a lot of build failures.

**Comment by mayhewsw** [comment]
Often it is this path missing: edu.jhu.util, or edu.jhu.gm. If I replace this with edu.jhu.pacaya.util, or edu.jhu.pacaya.gm, then it often works, but not always. For example, I can't find Alphabet class anywhere. 

Perhaps you are using new code that has been factored out of pacaya? If so, I don't know where to find this.

**Comment by wddabc** [comment]
Thanks. I'm looking into this.

**Comment by mayhewsw** [comment]
Alphabet appears to be similar to the FeatureNames class.

**Comment by wddabc** [comment]
Sorry for closing this accidentally. The problems turns out that my code was developed on an old version of pacaya (3.0.5) so it isn't compatible with the latest one (3.1.3). For now, for replicability, I prefer to releasing that old version than modifying my code. 

What I did is changing the pom.xml to point to the old version. As the old version is not on Maven repo, you have to manually copy the edu folder into the .m2/repository, then do mvn compile, as updated in the README.md.

The solution for now is crapy, I will ask the author of pacaya to put the old version on Maven. And I will fix the code to compatible with the new version.

**Comment by mayhewsw** [comment]
That is a little hacky, but it does compile now! Thanks for the fix.

**Comment by wddabc** [comment]
Hi, I have modified the code so that it is compatible with 3.1.3. For license reasons, we cannot release the temporary 3.0.5. Please check out the new update and remove the old .jars. Thanks!
